###Create Article MODERATOR
POST http://localhost:8080/article/moderator
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NzkwMTksImlkIjoiYzc1NjY3ZWQtNjYyOS00NGUyLWIzOTEtOGY5ZGFkNDhhNmM0Iiwicm9sZSI6IlJPTEVfVVNFUiIsInVzZXJuYW1lIjoicmFuZG9tRW1haWxAZ21haWwuY29tIiwiZXhwIjoxNzE3NzY1NDE5LCJpc3MiOiJLdW5VelRlc3QifQ.FpkmxCzWyxSs_jQtpNaqWZwXpfsUTD0MqO4xfsJfGh4dMkSa3SN9KVoTpl920rn4xEa_fus76p4c_hT4IH9htw

{
  "title": "createArticle",
  "description": "This article is a test article",
  "content": "Some article",
  "imageId": 1,
  "regionId": 1,
  "categoryId": 1,
  "publisherId": "UUID",
  "types": [1,2,3]
}

### Update article MODERATOR
POST http://localhost:8080/article/moderator/{{id}}
Content-Type: application/json

{
  "title": "new title",
  "description": "new description",
  "content": "some changes have been made",
  "sharedCount": 100000,
  "imageId": 1,
  "regionId": 2,
  "categoryId": 3,
  "publisherId": "uuid2",
  "types": [2]
}

### Delete by id MODERATOR
DELETE http://localhost:8080/article/delete/{{id}}

### Change status by id MODERATOR
PUT http://localhost:8080/article/status/{{id}}?status=NOT_PUBLISHED