###Create Article MODERATOR
POST http://localhost:8080/article/moderator
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2ODYwODYsImlkIjoiZGJlMjA1MjktODc5Yi00YjM5LWFkNjUtNGRmZDAyYmNiZDJhIiwicm9sZSI6IlJPTEVfTU9ERVJBVE9SIiwidXNlcm5hbWUiOiJyYW5kb21FbWFpbEBnbWFpbC5jb20iLCJleHAiOjE3MjAyNzgwODYsImlzcyI6Ikt1blV6VGVzdCJ9.AAyfFKqZlYIC5pHgS3UtnoP13zyrP_mp-SPprsVIYgfyKDPwqoPeoAMx2iathaPVnL96UONe4kK1goHy96pMgQ

{
  "title": "{{$random.alphabetic(10)}}",
  "description": "{{$random.alphabetic(10)}}",
  "content": "{{$random.alphabetic(10)}}",
  "imageId": 1,
  "regionId": 1,
  "categoryId": 1,
  "publisherId": "UUID",
  "types": [1,2,3]
}

### Update article MODERATOR
PUT http://localhost:8080/article/moderator/b6c74aa5-79a3-4ebe-ae2d-c157dfc5faa1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2ODYwODYsImlkIjoiZGJlMjA1MjktODc5Yi00YjM5LWFkNjUtNGRmZDAyYmNiZDJhIiwicm9sZSI6IlJPTEVfTU9ERVJBVE9SIiwidXNlcm5hbWUiOiJyYW5kb21FbWFpbEBnbWFpbC5jb20iLCJleHAiOjE3MjAyNzgwODYsImlzcyI6Ikt1blV6VGVzdCJ9.AAyfFKqZlYIC5pHgS3UtnoP13zyrP_mp-SPprsVIYgfyKDPwqoPeoAMx2iathaPVnL96UONe4kK1goHy96pMgQ

{
  "title": "{{$random.alphabetic(10)}} changed",
  "description": "{{$random.alphabetic(10)}} changed",
  "content": "{{$random.alphabetic(10)}} changed",
  "sharedCount": {{$random.integer(1000)}},
  "imageId": 1,
  "regionId": 2,
  "categoryId": 3,
  "publisherId": "uuid2",
  "types": [2, 4]
}

### Delete by id MODERATOR
DELETE http://localhost:8080/article/delete/{{id}}

### Change status by id MODERATOR
PUT http://localhost:8080/article/status/{{id}}?status=NOT_PUBLISHED