### Register to system
POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "dadaboymasharipov@gmail.com",
  "password": "123"
}


### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "login": "aliolimov@gmail.com",
  "password": "12345"
}