### Register to system
POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "{{$random.alphabetic(6)}}",
  "surname": "{{$random.alphabetic(6)}}",
  "email": "randomEmail@gmail.com",
  "password": "12345"
}

###Resend email
GET http://localhost:8080/auth/registration/resend/dadaboymasharipov512@gmail.com

### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "login": "randomEmail@gmail.com",
  "password": "12345"
}