### Create category
POST http://localhost:8080/category/adm/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NzcwMzEsImlkIjoiMDJmYjMwYjAtNWViYS00ZWJjLTllZTgtZDFkYWZhZWNjZjZiIiwicm9sZSI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6ImRhZGFib3ltYXNoYXJpcG92NTEyQGdtYWlsLmNvbSIsImV4cCI6MTcxNzc2MzQzMSwiaXNzIjoiS3VuVXpUZXN0In0.bHPzVbreLGh5H70VOQBCFqFOJM5mPTRJlwoK6l-79PtfE-G6_kCXtt_KdBtU8qUqEfRLLb_s7e8fCGG7Y2T_Vg

{
  "orderNumber": {{$random.integer(10)}},
  "nameUz": "{{$random.alphabetic(5)}} uz",
  "nameRu": "{{$random.alphabetic(5)}} ru",
  "nameEn": "{{$random.alphabetic(5)}} en"
}


### Get all category for ADMIN
GET http://localhost:8080/category/adm/all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NjA5MjIsImlkIjoiMDJmYjMwYjAtNWViYS00ZWJjLTllZTgtZDFkYWZhZWNjZjZiIiwicm9sZSI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6ImRhZGFib3ltYXNoYXJpcG92NTEyQGdtYWlsLmNvbSIsImV4cCI6MTcxNzc0NzMyMiwiaXNzIjoiS3VuVXpUZXN0In0.0rC1RZGnsQdZBMfs7nycNDSQn0e9cZehqNn6FvKqQUR5dooisL7_nKrOayRCae99JTGAML6TEASStaNeb2Tg1w

### Get all category by lang
GET http://localhost:8080/category/lang
Accept-Language: EN
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NjA5MjIsImlkIjoiMDJmYjMwYjAtNWViYS00ZWJjLTllZTgtZDFkYWZhZWNjZjZiIiwicm9sZSI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6ImRhZGFib3ltYXNoYXJpcG92NTEyQGdtYWlsLmNvbSIsImV4cCI6MTcxNzc0NzMyMiwiaXNzIjoiS3VuVXpUZXN0In0.0rC1RZGnsQdZBMfs7nycNDSQn0e9cZehqNn6FvKqQUR5dooisL7_nKrOayRCae99JTGAML6TEASStaNeb2Tg1w

### Update category by id
PUT http://localhost:8080/category/adm/update/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NjA5MjIsImlkIjoiMDJmYjMwYjAtNWViYS00ZWJjLTllZTgtZDFkYWZhZWNjZjZiIiwicm9sZSI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6ImRhZGFib3ltYXNoYXJpcG92NTEyQGdtYWlsLmNvbSIsImV4cCI6MTcxNzc0NzMyMiwiaXNzIjoiS3VuVXpUZXN0In0.0rC1RZGnsQdZBMfs7nycNDSQn0e9cZehqNn6FvKqQUR5dooisL7_nKrOayRCae99JTGAML6TEASStaNeb2Tg1w

{
  "orderNumber": {{$random.integer(10)}},
  "nameUz": "{{$random.alphabetic(5)}} changed uz",
  "nameRu": "{{$random.alphabetic(5)}} changed ru",
  "nameEn": "{{$random.alphabetic(5)}} changed en"
}

### Delete category by Id
DELETE http://localhost:8080/category/adm/delete/4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NjA5MjIsImlkIjoiMDJmYjMwYjAtNWViYS00ZWJjLTllZTgtZDFkYWZhZWNjZjZiIiwicm9sZSI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6ImRhZGFib3ltYXNoYXJpcG92NTEyQGdtYWlsLmNvbSIsImV4cCI6MTcxNzc0NzMyMiwiaXNzIjoiS3VuVXpUZXN0In0.0rC1RZGnsQdZBMfs7nycNDSQn0e9cZehqNn6FvKqQUR5dooisL7_nKrOayRCae99JTGAML6TEASStaNeb2Tg1w
