### Create region
POST localhost:8080/region/adm/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NjA5MjIsImlkIjoiMDJmYjMwYjAtNWViYS00ZWJjLTllZTgtZDFkYWZhZWNjZjZiIiwicm9sZSI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6ImRhZGFib3ltYXNoYXJpcG92NTEyQGdtYWlsLmNvbSIsImV4cCI6MTcxNzc0NzMyMiwiaXNzIjoiS3VuVXpUZXN0In0.0rC1RZGnsQdZBMfs7nycNDSQn0e9cZehqNn6FvKqQUR5dooisL7_nKrOayRCae99JTGAML6TEASStaNeb2Tg1w

{
  "orderNumber": {{$random.integer(10)}},
  "nameUz": "{{$random.alphabetic(5)}} uz",
  "nameRu": "{{$random.alphabetic(5)}} ru",
  "nameEn": "{{$random.alphabetic(5)}} en"
}

### Get all regions for ADMIN
GET http://localhost:8080/region/adm/all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NjA5MjIsImlkIjoiMDJmYjMwYjAtNWViYS00ZWJjLTllZTgtZDFkYWZhZWNjZjZiIiwicm9sZSI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6ImRhZGFib3ltYXNoYXJpcG92NTEyQGdtYWlsLmNvbSIsImV4cCI6MTcxNzc0NzMyMiwiaXNzIjoiS3VuVXpUZXN0In0.0rC1RZGnsQdZBMfs7nycNDSQn0e9cZehqNn6FvKqQUR5dooisL7_nKrOayRCae99JTGAML6TEASStaNeb2Tg1w


### Get all regions by lang
GET localhost:8080/region/lang
Accept-Language: EN

### Update region by Id
PUT http://localhost:8080/region/adm/update/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NjA5MjIsImlkIjoiMDJmYjMwYjAtNWViYS00ZWJjLTllZTgtZDFkYWZhZWNjZjZiIiwicm9sZSI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6ImRhZGFib3ltYXNoYXJpcG92NTEyQGdtYWlsLmNvbSIsImV4cCI6MTcxNzc0NzMyMiwiaXNzIjoiS3VuVXpUZXN0In0.0rC1RZGnsQdZBMfs7nycNDSQn0e9cZehqNn6FvKqQUR5dooisL7_nKrOayRCae99JTGAML6TEASStaNeb2Tg1w

{
  "orderNumber": {{$random.integer(10)}},
  "nameUz": "{{$random.alphabetic(5)}} changed uz",
  "nameRu": "{{$random.alphabetic(5)}} changed ru",
  "nameEn": "{{$random.alphabetic(5)}} changed en"
}

### Delete Region by Id
DELETE http://localhost:8080/region/adm/delete/4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NjA5MjIsImlkIjoiMDJmYjMwYjAtNWViYS00ZWJjLTllZTgtZDFkYWZhZWNjZjZiIiwicm9sZSI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6ImRhZGFib3ltYXNoYXJpcG92NTEyQGdtYWlsLmNvbSIsImV4cCI6MTcxNzc0NzMyMiwiaXNzIjoiS3VuVXpUZXN0In0.0rC1RZGnsQdZBMfs7nycNDSQn0e9cZehqNn6FvKqQUR5dooisL7_nKrOayRCae99JTGAML6TEASStaNeb2Tg1w