### Create type
POST http://localhost:8080/types/create
Content-Type: application/json

{
  "orderNumber": 10,
  "nameUz": "Type10 uz",
  "nameRu": "Type10 ru",
  "nameEn": "Type10 en"
}

### Get all types for ADMIN
GET http://localhost:8080/types/getAll

### Get all types by lang
GET http://localhost:8080/types/lang
Accept-Language: UZ

### Update type by id
PUT http://localhost:8080/types/update/6
Content-Type: application/json

{
  "orderNumber": 980,
  "nameUz": "Type4 uz",
  "nameRu": "Type4 ru",
  "nameEn": "Type4 en"
}

### Delete type by Id
DELETE http://localhost:8080/types/delete/6